*** Variables ***

${txtEmail}                                   viniciusferreira482@gmail.com
${txtPassword}                                123456
${txtEmailIncorreta}                          viniciusferreira482@gmail.com
${txtPasswordIncorreta}                       023456
${txtMsgInvalido}                             Authentication failed.
${txtProdutos}                                Faded Short Sleeve T-shirts
${txtProdutosIncorreto}                       sasasasa